### ISSUE TITLE
Drop noqa detection altogether

### ISSUE THREAD

**Issue by m-burst** [afonasev/flake8-plugin-utils#55]
Hi,

I suggest that this library should drop the noqa detection.
My rationale is:
* flake8 does it itself (at least since v3.0, maybe even earlier), and it probably does it more correctly, because it handles logical lines (i.e. line breaks with backslashes) rather than physical lines
* noqa detection is currently the major source of issues arising with the use of the library

I'll be happy to submit a PR if you agree with the idea.

**Comment by afonasev** [comment]
Hi, I will be happy to accept your PR!
