### ISSUE TITLE
argparse is deprecated in flake8@6 and compatible

### ISSUE THREAD

**Issue by DmytroLitvinov** [afonasev/flake8-plugin-utils#92]
Have the same issue as described here https://github.com/PyCQA/flake8/issues/1751

**Comment by DmytroLitvinov** [comment]
The solution is to remove `type='int'` and then convert to an integer inside the method `parse_options_to_config`.

**Comment by stefan6419846** [comment]
Do you have some more context on the actual error in your case? `flake8-plugin-utils` does not seem to use this construct, so this might be related to some other plugin using `flake8-plugin-utils`.

Additionally, the title appears to be wrong, as *flake8* migrated from *optparse* to *argparse* and *argparse*-style definitions are required now: https://github.com/pycqa/flake8/pull/1739

**Comment by DmytroLitvinov** [comment]
Ah.. sorry. My bad.

The issue itself is in another plugin.
We can close that issue.
